### ISSUE TITLE
Dashboard refresh causes user session logout

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#158]
As a user, I'm using the file-based authentication and simple authorization rules as attached below. After successful login, I'm able to access dashboard according to the defined permissions; however, when I reload the dashboard, I lose by login session and I'm redirected to login page instead.

```
security:
  basic:
    enabled: true
    realm: Spring Cloud Data Flow
spring:
  cloud:
    dataflow:
      security:
        authentication:
          file:
            enabled: true                                                 
            users:                                                        
              bob: bob, ROLE_MANAGE
              alice: alice, ROLE_VIEW, ROLE_CREATE
```
