### ISSUE TITLE
Search fails to load tasks when features are disabled

### ISSUE THREAD

**Issue by moritz31** [spring-cloud/spring-cloud-dataflow-ui#1629]
When some dataflow features are disabled and I try to search for a task, the search will not show the task.

**Reproduce:** 

```
 version: '3'

services:
  mysql:
    image: mysql:5.7.25
    container_name: dataflow-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: dataflow
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: rootpw
    expose:
      - 3306
      
  dataflow-server:
    image: springcloud/spring-cloud-dataflow-server:2.7.0
    container_name: dataflow-server
    ports:
      - "9393:9393"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/dataflow
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpw
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.mariadb.jdbc.Driver
      - SPRING_CLOUD_DATAFLOW_FEATURES_STREAMS_ENABLED=false
      - SPRING_CLOUD_DATAFLOW_FEATURES_SCHEDULES_ENABLED=false
      - SPRING_CLOUD_DATAFLOW_FEATURES_TASKS_ENABLED=true
      - SPRING_DATASOURCE_INITIALIZATION_MODE=always
    entrypoint: "./wait-for-it.sh mysql:3306 -- java -jar /maven/spring-cloud-dataflow-server.jar"
    volumes:
      - ${HOST_MOUNT_PATH:-.}:${DOCKER_MOUNT_PATH:-/root/scdf}
      - /var/run/docker.sock:/var/run/docker.sock
      
  app-import:
    image: springcloud/openjdk:2.0.0.RELEASE
    container_name: dataflow-app-import
    depends_on:
      - dataflow-server
    command: >
      /bin/sh -c "
        ./wait-for-it.sh -t 180 dataflow-server:9393;
        wget -qO- 'http://dataflow-server:9393/apps' --post-data='uri=${TASK_APPS_URI:-https://dataflow.spring.io/task-maven-latest&force=true}';
        echo 'Task apps imported'"
```  
With the following docker-compose one can start a simple dataflow stack.
     

1. Create a new task in the ui or with the shell (I created one named abc)
2. Search for the task in the searchbar ( The searchbar will show the tasks header but not show any task )

    
**Issue:** 

In my point of view the search code always except that streams and tasks are enabled. It does not validate in the frontend or backend if any feature is missing or the objects are null.

**Solution:** 

1. A quick and dirty solution would be, that the frontend uses the Safe Navigation Operator to validate that the stream object is null. This would result in the tasks been shown but still the frontend would throw errors because the streams could not be get.

2. A quite better option would be to know which features are enabled. Somehow the about page retrieves if streams or tasks are enabled and maybe this information could be used to not query tasks or streams at all if they are disabled.
